sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t szewczus/lab_8 -f Dockerfile .


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "lab8"
  env: "Lab8-env"
  bucket_name: "elasticbeanstalk-us-east-1-737706731656"
  bucket_path: "lab8"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
